# Generated by Django 2.1.1 on 2018-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='li',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=5)),
            ],
        ),
    ]
