# Generated by Django 2.1.1 on 2018-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=True, to='sex.li')),
            ],
        ),
    ]
