# Generated by Django 2.1.1 on 2018-10-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        ('sex', '0001_initial'),
        ('education', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField(null=True)),
                ('height', models.CharField(max_length=5,null=True)),
                ('marry', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('signature', models.CharField(max_length=200, null=True)),
                ('img_src', models.CharField(max_length=50, null=True)),
                ('edu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.li')),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.li')),
                ('sex', models.ForeignKey(on_delete=True, to='sex.li')),
            ],
        ),
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=100, null=True)),
                ('music', models.CharField(max_length=100, null=True)),
                ('film', models.CharField(max_length=100, null=True)),
                ('book', models.CharField(max_length=100, null=True)),
                ('pet', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='life',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drink', models.CharField(max_length=50, null=True)),
                ('smoke', models.CharField(max_length=50, null=True)),
                ('car', models.CharField(max_length=50, null=True)),
                ('cook', models.CharField(max_length=50, null=True)),
                ('housework', models.CharField(max_length=50, null=True)),
                ('parent', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=5,null=True)),
                ('constellation', models.CharField(max_length=20, null=True)),
                ('blood', models.CharField(max_length=10, null=True)),
                ('nation', models.CharField(max_length=10, null=True)),
                ('profession', models.CharField(max_length=20, null=True)),
                ('house', models.CharField(max_length=20, null=True)),
                ('school', models.CharField(max_length=20, null=True)),
                ('children', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
